export const joggers = [
  {
    title: "Oversized Jackson Joggers",
    discountedPrice: 999,
    price: 1999,
    reviewsAverage: 4.7,
    reviewsCount: 86,
    images: [
      "https://blinkbuy.s3.amazonaws.com/BlackJacksonJoggerNewWebImagecopy_0e508dce-a09e-4728-b573-24d80ad05f76.webp",
      "https://blinkbuy.s3.amazonaws.com/NewImagesJoggers-0011.webp",
      "https://blinkbuy.s3.amazonaws.com/OversizedFitImageJackson_d0ba1155-7ecc-47a9-870a-22a8356b1c03.webp",
      "https://blinkbuy.s3.amazonaws.com/c172988da79f1741560913374389fda3_2.webp",
    ],
    tags: [
      "app_size_chart",
      "B2G1allmen",
      "BS-MEN",
      "BS-Plain-Tee",
      "classNameic Crew Tees",
      "classNameicCrew",
      "Clearance-Men-Jan23",
      "discount",
      "good",
      "jockey",
      "male",
      "Men",
      "Men Plain Tees",
      "menplaintees",
      "MSS-Feb24",
      "NBB25NBB5",
      "Plain",
      "puma",
      "ret",
      "Size-L",
      "Size-M",
      "Size-S",
      "Size-XL",
      "Size-XXL",
      "Size-XXXL",
      "Summer-Soch",
      "t sh",
      "t shi",
      "t shir",
      "T-Shirt",
      "tees",
      "testinv",
      "topi",
      "Topwear",
      "tshi",
      "tshir",
      "tshirt",
      "tshirts",
    ],
    colors: ["Navy Blue", "Black"],
    sizes: ["S", "M", "L", "XL", "XXL"],
  },
  {
    title: "Oversized Cargo Joggers",
    discountedPrice: 999,
    price: 1999,
    reviewsAverage: 4.7,
    reviewsCount: 97,
    images: [
      "https://blinkbuy.s3.amazonaws.com/Black1.webp",
      "https://blinkbuy.s3.amazonaws.com/Black3_714855d5-9c25-46d2-9c89-39f607564a16.webp",
      "https://blinkbuy.s3.amazonaws.com/Black5.webp",
      "https://blinkbuy.s3.amazonaws.com/Black4_411df400-f170-491b-acf7-611a4324c706.webp",
      "https://blinkbuy.s3.amazonaws.com/NewImagesJoggers-0001.webp",
      "https://blinkbuy.s3.amazonaws.com/Black2.webp",
    ],
    tags: [
      "2021BS",
      "act-men-so24",
      "All-MenCat23",
      "AllJoggerPDP",
      "app_size_chart",
      "B2G1allmen",
      "Best Seller",
      "botto",
      "Bottomwear",
      "BS-Men-Bottom",
      "BS-Men-Joggers",
      "CargoPocketJoggers",
      "Clearance-Men-Jan23",
      "denim",
      "discount",
      "fash.jogger",
      "Fitness",
      "good",
      "Jog.cordfeb23",
      "jogers",
      "jogg",
      "joggers",
      "joggers for w",
      "jogges",
      "jogging",
      "johg",
      "johgers",
      "lower",
      "lowers",
      "M.elevated_joggers",
      "m.jogger",
      "M.Restock.Jogger",
      "male",
      "Men",
      "men botto",
      "Men-Jogger",
      "MenJogger2023",
      "MenJogger@23",
      "MenJogPlains",
      "mens bott",
      "mens oversized jogger",
      "MJOGPUR77199",
      "MSS-Feb24",
      "NBB25NBB5",
      "night",
      "night pants",
      "night wear",
      "nike",
      "NJCollection",
      "NMJV2",
      "NOJoggers",
      "oversized",
      "Oversized.Cargo.Joggers",
      "pajama",
      "pant",
      "pants",
      "pyjama",
      "pyjamas",
      "ret",
      "running",
      "Size-L",
      "Size-M",
      "Size-S",
      "Size-XL",
      "Size-XXL",
      "Size-XXXL",
      "Skultcollection",
      "SochMencat",
      "Socioh-MenCat",
      "SociohJogCord",
      "sweat pant",
      "sweat pants",
      "sweatpant",
      "sweatpants",
      "testinv",
      "TopMenJOG",
      "trac",
      "track p",
      "track pa",
      "track pan",
      "trousers",
    ],
    colors: [
      "Black",
      "Olive Green",
      "Arctic Wolf",
      "Eiffel Tower",
      "Grey Melange",
      "Powder Blue",
      "Navy Blue",
      "Dark Oak",
    ],
    sizes: ["S", "M", "XL", "XXL"],
  },
  {
    title: "Oversized Vintage Wash Joggers",
    discountedPrice: 999,
    price: 1999,
    reviewsAverage: 5.0,
    reviewsCount: 44,
    images: [
      "https://blinkbuy.s3.amazonaws.com/2_cb13f10c-f127-45b0-b9ed-a79928104d0f.webp",
      "https://blinkbuy.s3.amazonaws.com/3_9cd96d55-8100-43cd-922e-ee2847bbc06a.webp",
      "https://blinkbuy.s3.amazonaws.com/1_f7ba946d-e27e-476c-8c35-42924be098da.webp",
      "https://blinkbuy.s3.amazonaws.com/VintageWashBGImages1_b7e18701-bbf2-491a-8138-e08331e56b02.webp",
      "https://blinkbuy.s3.amazonaws.com/4_1b6571fd-c66f-4642-8376-dc31079f443d.webp",
    ],
    tags: [
      "2021BS",
      "act-men-so24",
      "All-MenCat23",
      "AllJoggerPDP",
      "app_size_chart",
      "B2G1allmen",
      "Best Seller",
      "botto",
      "Bottomwear",
      "BS-Men-Bottom",
      "BS-Men-Joggers",
      "Clearance-Men-Jan23",
      "denim",
      "discount",
      "fash.jogger",
      "Fitness",
      "good",
      "Jog.cordfeb23",
      "jogers",
      "jogg",
      "joggers",
      "joggers for w",
      "jogges",
      "jogging",
      "johg",
      "johgers",
      "lower",
      "lowers",
      "M.elevated_joggers",
      "m.jogger",
      "M.Restock.Jogger",
      "male",
      "Men",
      "men botto",
      "Men-Jogger",
      "MenJogger2023",
      "MenJogger@23",
      "MenJogPlains",
      "mens bott",
      "mens oversized jogger",
      "MJOGPUR77199",
      "MSS-Feb24",
      "NBB25NBB5",
      "night",
      "night pants",
      "night wear",
      "nike",
      "NJCollection",
      "NMJV2",
      "NOJoggers",
      "oversized",
      "pajama",
      "pant",
      "pants",
      "pyjama",
      "pyjamas",
      "ret",
      "running",
      "Size-L",
      "Size-M",
      "Size-S",
      "Size-XL",
      "Size-XXL",
      "Size-XXXL",
      "Skultcollection",
      "SochMencat",
      "Socioh-MenCat",
      "SociohJogCord",
      "sweat pant",
      "sweat pants",
      "sweatpant",
      "sweatpants",
      "testinv",
      "TopMenJOG",
      "trac",
      "track p",
      "track pa",
      "track pan",
      "trousers",
    ],
    colors: ["Black", "Gravity Grey"],
    sizes: ["S", "M", "L", "XL", "XXL"],
  },
  {
    title: "Zip-Pocket Joggers",
    discountedPrice: 899,
    price: 1999,
    reviewsAverage: 4.6,
    reviewsCount: 84,
    images: [
      "https://blinkbuy.s3.amazonaws.com/ZipPocketJoggersMen8.webp",
      "https://blinkbuy.s3.amazonaws.com/ZipPocketJoggersMen4_5a7b2268-626f-4ff9-a825-51d56eae57f5.webp",
      "https://blinkbuy.s3.amazonaws.com/ZipPocketJoggersMen3_49886ffa-996e-4632-9bec-5e16a6ea2236.webp",
      "https://blinkbuy.s3.amazonaws.com/ZipPocketJoggersMen5_71e08f67-c3e4-4fc2-9aa7-0ba83f15e83e.webp",
      "https://blinkbuy.s3.amazonaws.com/AWZipWebcopy_5fd15f88-9994-43e3-ace0-0ff114be42b0.webp",
    ],
    tags: [
      "2021BS",
      "act-men-so24",
      "All-MenCat23",
      "AllJoggerPDP",
      "app_size_chart",
      "B2G1allmendraft",
      "Best Seller",
      "botto",
      "Bottomwear",
      "BS-Men-Bottom",
      "BS-Men-Joggers",
      "Clearance-Men-Jan23",
      "denim",
      "discount",
      "Fitness",
      "good",
      "Jog.cordfeb23",
      "jogers",
      "jogg",
      "Jogger",
      "joggers",
      "joggers for w",
      "JoggersP3",
      "jogges",
      "jogging",
      "johg",
      "johgers",
      "lower",
      "lowers",
      "m.jogger",
      "M.Restock.Jogger",
      "M.Restock.V2",
      "male",
      "Men",
      "men botto",
      "Men-Jogger",
      "MenJogger2023",
      "MenJogger@23",
      "MenJogPlains",
      "MenNewMockup",
      "mens bott",
      "MJ@1999",
      "MJ@B2G1",
      "MJOGPUR77199",
      "MSS-Feb24",
      "NBB25NBB5",
      "New_Arrivals",
      "night",
      "night pants",
      "night wear",
      "nike",
      "NJCollection",
      "NMJV2",
      "NOJoggers",
      "pajama",
      "pant",
      "pants",
      "pyjama",
      "pyjamas",
      "ret",
      "running",
      "Size-L",
      "Size-M",
      "Size-S",
      "Size-XL",
      "Size-XXL",
      "Size-XXXL",
      "Skultcollection",
      "SochMencat",
      "Socioh-MenCat",
      "SociohJogCord",
      "sweat pant",
      "sweat pants",
      "sweatpant",
      "sweatpants",
      "testinv",
      "trac",
      "track p",
      "track pa",
      "track pan",
      "trousers",
      "zs.joggers",
    ],
    colors: [
      "Arctic Wolf",
      "Olive Green",
      "Grey Melange",
      "Black",
      "Navy Blue",
      "Powder Blue",
      "Dark Oak",
      "Eiffel Tower",
    ],
    sizes: ["S", "M", "L", "XL", "XXL"],
  },
  {
    title: "Oversized Cargo Joggers",
    discountedPrice: 999,
    price: 1999,
    reviewsAverage: 4.7,
    reviewsCount: 97,
    images: [
      "https://blinkbuy.s3.amazonaws.com/7_ac13864a-a402-43f9-b76b-ccb3fab4e17b.webp",
      "https://blinkbuy.s3.amazonaws.com/4_bc692f99-6fc5-4fa5-b2d0-5ebe7d348efc.webp",
      "https://blinkbuy.s3.amazonaws.com/NewImagesJoggers-0002.webp",
      "https://blinkbuy.s3.amazonaws.com/1_c550323d-4199-4c3b-8fbd-2a789ff6dc63.webp",
      "https://blinkbuy.s3.amazonaws.com/3_9e11671c-dd26-47ab-b18c-c88c30edb474.webp",
      "https://blinkbuy.s3.amazonaws.com/OliveGreen3.webp",
      "https://blinkbuy.s3.amazonaws.com/5_b4a84988-dd71-43f2-bff9-013f4fee9093.webp",
    ],
    tags: [
      "2021BS",
      "act-men-so24",
      "All-MenCat23",
      "AllJoggerPDP",
      "app_size_chart",
      "B2G1allmen",
      "Best Seller",
      "botto",
      "Bottomwear",
      "BS-Men-Bottom",
      "BS-Men-Joggers",
      "CargoPocketJoggers",
      "Clearance-Men-Jan23",
      "denim",
      "discount",
      "fash.jogger",
      "Fitness",
      "good",
      "Jog.cordfeb23",
      "jogers",
      "jogg",
      "joggers",
      "joggers for w",
      "jogges",
      "jogging",
      "johg",
      "johgers",
      "lower",
      "lowers",
      "M.elevated_joggers",
      "m.jogger",
      "M.Restock.Jogger",
      "male",
      "Men",
      "men botto",
      "Men-Jogger",
      "MenJogger2023",
      "MenJogger@23",
      "MenJogPlains",
      "mens bott",
      "mens oversized jogger",
      "MJOGPUR77199",
      "MSS-Feb24",
      "NBB25NBB5",
      "night",
      "night pants",
      "night wear",
      "nike",
      "NJCollection",
      "NMJV2",
      "NOJoggers",
      "oversized",
      "Oversized.Cargo.Joggers",
      "pajama",
      "pant",
      "pants",
      "pyjama",
      "pyjamas",
      "ret",
      "running",
      "Size-L",
      "Size-M",
      "Size-S",
      "Size-XL",
      "Size-XXL",
      "Size-XXXL",
      "Skultcollection",
      "SochMencat",
      "Socioh-MenCat",
      "SociohJogCord",
      "sweat pant",
      "sweat pants",
      "sweatpant",
      "sweatpants",
      "testinv",
      "TopMenJOG",
      "trac",
      "track p",
      "track pa",
      "track pan",
      "trousers",
    ],
    colors: [
      "Olive Green",
      "Black",
      "Arctic Wolf",
      "Grey Melange",
      "Eiffel Tower",
      "Powder Blue",
      "Navy Blue",
      "Dark Oak",
    ],
    sizes: ["S", "M", "L", "XL", "XXL"],
  },
  {
    title: "Jordan Men Joggers",
    discountedPrice: 999,
    price: 1999,
    reviewsAverage: 4.7,
    reviewsCount: 86,
    images: [
      "https://blinkbuy.s3.amazonaws.com/1628066934c1a74bfc12c3472981dc3c82fef9bbf2_1.webp",
      "https://blinkbuy.s3.amazonaws.com/1628066939d43f58cb12ec29bb53561d9c5120e4e1.jpeg",
      "https://blinkbuy.s3.amazonaws.com/87_fcd49f2a-ad75-48a0-97e7-923286dffa9c.jpg",
      "https://blinkbuy.s3.amazonaws.com/88_aa4b4abd-9dd1-4ca1-b523-bee35c49345a.webp",
      "https://blinkbuy.s3.amazonaws.com/1711517700660.webp",
      "https://blinkbuy.s3.amazonaws.com/162806693725591753d95762ede14b0323354c4491_1.webp",
      "https://blinkbuy.s3.amazonaws.com/1628066931dbce5b8eb43dc13287b8fdd7b9fef57f_1.webp",
    ],
    tags: [
      "2021BS",
      "30BestMen",
      "act-men-so24",
      "AK77199",
      "All-MenCat23",
      "AllJoggerPDP",
      "app_size_chart",
      "B2G1allmen",
      "botto",
      "Bottomwear",
      "BS-Men-Bottom",
      "BS-Men-Joggers",
      "denim",
      "discount",
      "fash.jogger",
      "fash.joggers",
      "Fitness",
      "good",
      "Jog.Cord23",
      "Jog.cordfeb23",
      "jogers",
      "jogg",
      "Jogger",
      "jogger2499",
      "joggers",
      "joggers for w",
      "jogges",
      "jogging",
      "johg",
      "johgers",
      "lower",
      "lowers",
      "M.Bot.23",
      "m.jogger",
      "M.Restock.Jogger",
      "male",
      "Men",
      "men botto",
      "Men-Jogger",
      "MenJogger@23",
      "menjoggers@23",
      "mens bott",
      "MensButton",
      "MJOGPUR77199",
      "MSS-Feb24",
      "NBB25NBB5",
      "night",
      "night pants",
      "night wear",
      "nike",
      "NJCollection",
      "NOJoggers",
      "pajama",
      "pant",
      "pants",
      "pyjama",
      "pyjamas",
      "ret",
      "running",
      "Size-L",
      "Size-M",
      "Size-S",
      "Size-XL",
      "Size-XXL",
      "Size-XXXL",
      "Skultcollection",
      "SochMencat",
      "Socioh-MenCat",
      "SociohJogCord",
      "sweat pant",
      "sweat pants",
      "sweatpant",
      "sweatpants",
      "testinv",
      "Toberefilled",
      "Top10MenJOG",
      "Top50DPA",
      "topM.cordBot",
      "TopMenJOG",
      "trac",
      "track p",
      "track pa",
      "track pan",
      "trending_nb",
      "trousers",
    ],
    colors: ["Grey Melange"],
    sizes: ["S", "M", "L", "XL", "XXL"],
  },
  {
    title: "Black Zip Pocket Shorts",
    discountedPrice: 699,
    price: 1399,
    reviewsAverage: null,
    reviewsCount: null,
    images: [
      "https://blinkbuy.s3.amazonaws.com/WebImagesNew1_e6bf03c9-3510-49b1-8be7-cd7903deb89f.webp",
      "https://blinkbuy.s3.amazonaws.com/WebImagesNew3_f2ce2665-c47e-436d-8265-a6bdaeaac0a8.webp",
      "https://blinkbuy.s3.amazonaws.com/WebImagesNew7_9c79167a-5ad0-406d-94d8-a7303b1d3711.webp",
      "https://blinkbuy.s3.amazonaws.com/WebImagesNew5_0d621482-4531-4383-9150-2a22a02b5be8.webp",
      "https://blinkbuy.s3.amazonaws.com/WebImagesNew6_f971c0d5-c26d-4062-a9a3-7e0c4eab2ebe.webp",
      "https://blinkbuy.s3.amazonaws.com/WebImagesNew4_8853afbe-ff27-47ac-a2fc-9aac65f283a7.webp",
    ],
    tags: [
      "2021BS",
      "All-MenCat23",
      "AllShortPDP",
      "app_size_chart",
      "B2G1allmen",
      "botto",
      "Bottomwear",
      "boxer",
      "boxers",
      "BS-Men-Bottom",
      "BS-Men-Shorts",
      "Buy2",
      "Buy222",
      "casual",
      "Clearance-Men-Jan23",
      "Comfort Shorts",
      "denim",
      "discount",
      "EBShorts",
      "Fitness",
      "good",
      "half pant",
      "half pants",
      "Jog.cordfeb23",
      "M.Restock.Jogger",
      "male",
      "Men",
      "Men-Shorts",
      "mens shorts",
      "MS3@1499",
      "MS@1199",
      "MS@999",
      "MSD@999",
      "MShortsV2",
      "MSS-Feb24",
      "MZIP@1199",
      "NBB25NBB5",
      "night wear",
      "NMSV2",
      "NOShorts",
      "ret",
      "running",
      "shor",
      "short",
      "Short999",
      "Shorts",
      "shorts f",
      "ShortsP2",
      "shot",
      "shots",
      "Size-L",
      "Size-M",
      "Size-S",
      "Size-XL",
      "Size-XXL",
      "Size-XXXL",
      "Skultcollection",
      "sort@999",
      "Summer-Soch",
      "testinv",
      "three fourth",
      "V2.Shorts.Restock",
    ],
    colors: [
      "Black",
      "Navy Blue",
      "Olive Green",
      "Grey Melange",
      "Arctic Wolf",
      "Powder Blue",
      "Oat Milk",
    ],
    sizes: ["S", "M", "L"],
  },
  {
    title: "Morphin Shorts",
    discountedPrice: 799,
    price: 1499,
    reviewsAverage: null,
    reviewsCount: null,
    images: [
      "https://blinkbuy.s3.amazonaws.com/04259f7a4d0f36f6e5b90b08a9892e19_8c3ced53-c1c3-482c-81ed-bbb0720b4214.webp",
      "https://blinkbuy.s3.amazonaws.com/MorphinWebIMG1_e1919212-5df2-4aed-a985-e0cacfce2841.webp",
      "https://blinkbuy.s3.amazonaws.com/Vanquish-Mens-Contrast-Grey-Shorts-3_5000x_ab47c2c7-8d52-4bd2-9c87-805a8dcec67b.webp",
      "https://blinkbuy.s3.amazonaws.com/MorphinWebIMG2_3eece38e-8535-4882-8113-33ec6de1b056.webp",
      "https://blinkbuy.s3.amazonaws.com/Vanquish-Mens-Contrast-Grey-Shorts-1_5000x_925c42ae-b916-4688-affc-e45b4c3977b1.webp",
    ],
    tags: [
      "2021BS",
      "AllJoggerPDP",
      "app_size_chart",
      "B2G1allmendraft",
      "botto",
      "Bottomwear",
      "boxer",
      "boxers",
      "BS-Men-Bottom",
      "BS-Men-Shorts",
      "casual",
      "Clearance-Men-Jan23",
      "denim",
      "discount",
      "Fitness",
      "good",
      "half pant",
      "half pants",
      "Jog.cordfeb23",
      "M.Restock.Jogger",
      "male",
      "Men",
      "Men-Shorts",
      "menjoggers@23",
      "mens shorts",
      "MS@999",
      "MSD@1199",
      "MshortsUnder599",
      "MSS-Feb24",
      "NBB25NBB5",
      "night wear",
      "NOShorts",
      "ret",
      "running",
      "shor",
      "short",
      "Short999",
      "shortpdp",
      "Shorts",
      "shorts f",
      "shot",
      "shots",
      "Size-L",
      "Size-M",
      "Size-S",
      "Size-XL",
      "Size-XXL",
      "Size-XXXL",
      "sort@999",
      "Summer-Soch",
      "testinv",
      "three fourth",
    ],
    colors: ["Grey Melange", "Black"],
    sizes: ["S", "M"],
  },
  {
    title: "Oversized Cargo Joggers",
    discountedPrice: 999,
    price: 1999,
    reviewsAverage: 4.7,
    reviewsCount: 97,
    images: [
      "https://blinkbuy.s3.amazonaws.com/6_1b4456ab-3aea-460c-9151-4317be1431a8.jpg",
      "https://blinkbuy.s3.amazonaws.com/3Opction2_db7467df-6840-40e6-8fc8-eeb54f7475a0.webp",
      "https://blinkbuy.s3.amazonaws.com/2_bd40584c-d2c7-4381-9af2-bfb06993e650.webp",
      "https://blinkbuy.s3.amazonaws.com/4_4c4166e5-66c4-4e89-bc6a-402d5c1ddde9.webp",
      "https://blinkbuy.s3.amazonaws.com/5_a54826a4-2d79-4f36-8479-c92133ca6746.jpg",
      "https://blinkbuy.s3.amazonaws.com/1712335316643_1.webp",
    ],
    tags: [
      "2021BS",
      "act-men-so24",
      "All-MenCat23",
      "AllJoggerPDP",
      "app_size_chart",
      "B2G1allmen",
      "Best Seller",
      "botto",
      "Bottomwear",
      "BS-Men-Bottom",
      "BS-Men-Joggers",
      "CargoPocketJoggers",
      "Clearance-Men-Jan23",
      "denim",
      "discount",
      "fash.jogger",
      "Fitness",
      "good",
      "Jog.cordfeb23",
      "jogers",
      "jogg",
      "joggers",
      "joggers for w",
      "jogges",
      "jogging",
      "johg",
      "johgers",
      "lower",
      "lowers",
      "M.elevated_joggers",
      "m.jogger",
      "M.Restock.Jogger",
      "male",
      "Men",
      "men botto",
      "Men-Jogger",
      "MenJogger2023",
      "MenJogger@23",
      "MenJogPlains",
      "mens bott",
      "mens oversized jogger",
      "MJOGPUR77199",
      "MSS-Feb24",
      "NBB25NBB5",
      "night",
      "night pants",
      "night wear",
      "nike",
      "NJCollection",
      "NMJV2",
      "NOJoggers",
      "oversized",
      "Oversized.Cargo.Joggers",
      "pajama",
      "pant",
      "pants",
      "pyjama",
      "pyjamas",
      "ret",
      "running",
      "Size-L",
      "Size-M",
      "Size-S",
      "Size-XL",
      "Size-XXL",
      "Size-XXXL",
      "Skultcollection",
      "SochMencat",
      "Socioh-MenCat",
      "SociohJogCord",
      "sweat pant",
      "sweat pants",
      "sweatpant",
      "sweatpants",
      "testinv",
      "TopMenJOG",
      "trac",
      "track p",
      "track pa",
      "track pan",
      "trousers",
    ],
    colors: [
      "Grey Melange",
      "Olive Green",
      "Black",
      "Arctic Wolf",
      "Eiffel Tower",
      "Powder Blue",
      "Navy Blue",
      "Dark Oak",
    ],
    sizes: ["S", "M", "L", "XL", "XXL"],
  },
  {
    title: "Miez Men Joggers",
    discountedPrice: 999,
    price: 1999,
    reviewsAverage: 4.8,
    reviewsCount: 64,
    images: [
      "https://blinkbuy.s3.amazonaws.com/1712335316643_1.webp",
      "https://blinkbuy.s3.amazonaws.com/1619499944e094f83305af81b7c74f8bcc228d77e4_1d8f3fc8-6215-4821-989d-9107c8f50738.webp",
      "https://blinkbuy.s3.amazonaws.com/MiezNewFrontcopy.webp",
      "https://blinkbuy.s3.amazonaws.com/1619499937ae898beeaa49137332390cee7fca019f_bf40edcc-8330-4931-a607-cef02c187f38.webp",
    ],
    tags: [
      "2021BS",
      "act-men-so24",
      "All-MenCat23",
      "AllJoggerPDP",
      "app_size_chart",
      "botto",
      "Bottomwear",
      "BS-Men-Bottom",
      "BS-Men-Joggers",
      "denim",
      "discount",
      "fash.jogger",
      "fash.joggers",
      "Fitness",
      "good",
      "Jog.cordfeb23",
      "jogers",
      "jogg",
      "joggers for w",
      "jogging",
      "johg",
      "lower",
      "lowers",
      "M.Bot.23",
      "m.jogger",
      "M.Restock.Jogger",
      "male",
      "Men",
      "men botto",
      "men oversized jogger",
      "Men-Jogger",
      "MenJogger2023",
      "MenJogger@23",
      "mens bott",
      "MensButton",
      "MJOGPUR77199",
      "MSS-Feb24",
      "NBB25NBB5",
      "night",
      "night pants",
      "night wear",
      "nike",
      "NJCollection",
      "NOJoggers",
      "pajama",
      "pant",
      "pants",
      "pyjama",
      "pyjamas",
      "ret",
      "running",
      "Size-L",
      "Size-M",
      "Size-S",
      "Size-XL",
      "Size-XXL",
      "Size-XXXL",
      "Skultcollection",
      "SochMencat",
      "Socioh-MenCat",
      "SociohJogCord",
      "sweat pant",
      "sweat pants",
      "sweatpant",
      "sweatpants",
      "testinv",
      "Top50DPA",
      "TopMenJOG",
      "trac",
      "track p",
      "track pa",
      "track pan",
      "trousers",
    ],
    colors: ["Navy Blue", "Maroon", "Royal Blue"],
    sizes: ["S", "M", "L", "XL", "XXL"],
  },
];

export const co_ords = [
  {
    title: "Oversized Cooper Utility Co-Ord",
    discountedPrice: 1599,
    price: 3199,
    reviewsAverage: null,
    reviewsCount: null,
    colors: ["Navy Blue"],
    images: [
      "https://blinkbuy.s3.amazonaws.com/WhatsAppImage2024-04-24at3.59.09PM.webp",
      "https://blinkbuy.s3.amazonaws.com/WhatsAppImage2024-04-24at2.59.05PM.webp",
      "https://blinkbuy.s3.amazonaws.com/WhatsAppImage2024-04-24at2.33.30PM_6d142f58-4e9b-414d-af45-0ed23039b109.webp",
      "https://blinkbuy.s3.amazonaws.com/WhatsAppImage2024-04-24at2.53.58PM.webp",
      "https://blinkbuy.s3.amazonaws.com/WhatsAppImage2024-04-24at2.33.30PM_1_4ba2ce96-9116-4f42-b18b-f3229671d5b7.webp",
    ],
    tags: [
      "act-men-so24",
      "All-MenCat23",
      "AllCoordPDP",
      "Co-ord",
      "discount",
      "good",
      "Jog.cordfeb23",
      "M.cord",
      "m.elevated_coords",
      "m.mono",
      "male",
      "Men",
      "Menmccord",
      "Mennewcoll771",
      "Mens Coord set",
      "Mono-coords",
      "MSS-Feb24",
      "NBB25NBB5",
      "NOCoord",
      "oversized",
      "ret",
      "Size-L",
      "Size-M",
      "Size-S",
      "Size-XL",
      "Size-XXL",
      "Size-XXXL",
    ],
    sizes: ["S", "L", "XL", "XXL"],
  },
  {
    title: "Hwak Men's Co-Ord Sets",
    discountedPrice: 1599,
    price: 3199,
    reviewsAverage: 4.6,
    reviewsCount: 55,
    colors: ["Olive Green"],
    images: [
      "https://blinkbuy.s3.amazonaws.com/1647565150024f34cac337e8f3d58da86854ad9778.webp",
      "https://blinkbuy.s3.amazonaws.com/1647565145e111ca632277aa8dbc7d41d1f9e84e4b.webp",
      "https://blinkbuy.s3.amazonaws.com/1647565148b1ff79ecc50e4dee2b41e8a0b17da10a.webp",
      "https://blinkbuy.s3.amazonaws.com/16475651511512e3c66e989f735ab443c9bddfc5f2.webp",
      "https://blinkbuy.s3.amazonaws.com/16475651472a3a03072e3ec8cbca64508a75a74b48.webp",
      "https://blinkbuy.s3.amazonaws.com/WhatsAppImage2024-04-06at2.09.47PM_1.jpg",
    ],
    tags: [
      "31-80Men",
      "act-men-so24",
      "All-MenCat23",
      "AllCoordPDP",
      "Best_Seller_NB",
      "Co-ord",
      "discount",
      "good",
      "Jog.Cord23",
      "M.cord",
      "male",
      "MCORDPUR77199",
      "Men",
      "mennoberodrop4",
      "Mens Coord set",
      "MensButton",
      "MSS-Feb24",
      "NBB25NBB5",
      "NOCoord",
      "ret",
      "Size-L",
      "Size-M",
      "Size-S",
      "Size-XL",
      "Size-XXL",
      "Size-XXXL",
      "SochMencat",
      "Socioh-MenCat",
      "SociohJogCord",
      "SummerCordMen",
      "SummerCordMens",
      "testinv",
      "topM.cordBot",
    ],
    sizes: ["S", "M", "L", "XL", "XXL"],
  },
  {
    title: "Oversized Cargo Shorts Co-Ord",
    discountedPrice: 1799,
    price: 2599,
    reviewsAverage: null,
    reviewsCount: null,
    colors: ["Navy Blue"],
    images: [
      "https://blinkbuy.s3.amazonaws.com/WhatsAppImage2024-04-05at4.00.02PM_5_5671e43b-2d0f-4534-a0ee-de9364fff027.webp",
      "https://blinkbuy.s3.amazonaws.com/WhatsAppImage2024-04-05at4.00.02PM_6_42338ec0-d15e-406b-9365-51b631a97ff1.webp",
      "https://blinkbuy.s3.amazonaws.com/WhatsAppImage2024-04-05at4.00.02PM_2_4f2d5460-b517-4286-9489-8ddeaa142d60.jpg",
      "https://blinkbuy.s3.amazonaws.com/WhatsAppImage2024-04-05at4.00.03PM_5_628e170b-a45c-4a30-93f1-46652c3127f7.webp",
      "https://blinkbuy.s3.amazonaws.com/WhatsAppImage2024-04-05at4.00.02PM_9_c2da64d1-d1b2-47ae-9cda-1bf188323e42.jpg",
      "https://blinkbuy.s3.amazonaws.com/7_740cabe6-1e5f-40e3-ae5f-0426c3627843.jpg",
      "https://blinkbuy.s3.amazonaws.com/WhatsAppImage2024-04-05at4.00.03PM_2_6a26edc0-e19f-48da-8fa5-ac1e15f06caf.jpg",
      "https://blinkbuy.s3.amazonaws.com/WhatsAppImage2024-04-05at4.00.03PM_3_cd41c2c5-be6b-4861-b4f5-f420bff0a848.webp",
    ],
    tags: [
      "act-men-so24",
      "All-MenCat23",
      "AllCoordPDP",
      "Co-ord",
      "discount",
      "good",
      "Jog.cordfeb23",
      "M.cord",
      "m.elevated_coords",
      "m.mono",
      "male",
      "Men",
      "Menmccord",
      "Mennewcoll771",
      "Mens Coord set",
      "Mono-coords",
      "MSS-Feb24",
      "NBB25NBB5",
      "NOCoord",
      "oversized",
      "ret",
      "Size-L",
      "Size-M",
      "Size-S",
      "Size-XL",
      "Size-XXL",
      "Size-XXXL",
    ],
    sizes: ["S", "M", "L", "XL", "XXL"],
  },
  {
    title: "Juan Men's Co-Ord Set",
    discountedPrice: 1899,
    price: 3799,
    reviewsAverage: 5.0,
    reviewsCount: 1,
    colors: ["White, Grey"],
    images: [
      "https://blinkbuy.s3.amazonaws.com/8_121ba356-b882-4ea5-acc1-ef708598e644.jpg",
      "https://blinkbuy.s3.amazonaws.com/6_46a1ade4-3715-4f46-a265-5bc23c94a7e9.webp",
      "https://blinkbuy.s3.amazonaws.com/2_8208ec56-1bc7-4c94-a9ba-13e86ca43518.webp",
      "https://blinkbuy.s3.amazonaws.com/4_f27165a7-143a-4d6c-a0e0-c0c15ae9fb2d.webp",
      "https://blinkbuy.s3.amazonaws.com/7_d620babc-2170-467e-a16d-7ac248620807.webp",
      "https://blinkbuy.s3.amazonaws.com/1_b0bedba1-ffc2-4d62-b94f-0713c5c6d6c9.webp",
    ],
    tags: [
      "23Clearance",
      "act-men-so24",
      "AllCoordPDP",
      "Co-ord",
      "discount",
      "good",
      "hoodiedropsale",
      "Jog.Cord23",
      "M.cord",
      "male",
      "MAutumn",
      "MCORDPUR77199",
      "Men",
      "Mens Coord set",
      "MSS-Feb24",
      "NBB25NBB5",
      "New_Arrivals",
      "NOCoord",
      "ret",
      "Size-L",
      "Size-M",
      "Size-S",
      "Size-XL",
      "Size-XXL",
      "Size-XXXL",
      "SochMencat",
      "Socioh-MenCat",
      "SociohJogCord",
      "testinv",
      "topM.cordBot",
    ],
    sizes: ["S", "M", "L", "XL", "XXL"],
  },
  {
    title: "Wilder Co-Ord Set",
    discountedPrice: 1399,
    price: 2599,
    reviewsAverage: null,
    reviewsCount: null,
    colors: null,
    images: [
      "https://blinkbuy.s3.amazonaws.com/WhatsAppImage2024-04-24at12.48.43PM_1%20(1).webp",
      "https://blinkbuy.s3.amazonaws.com/WhatsAppImage2024-04-24at12.48.43PM_1.webp",
      "https://blinkbuy.s3.amazonaws.com/WhatsAppImage2024-04-24at12.48.43PM.webp",
      "https://blinkbuy.s3.amazonaws.com/WhatsAppImage2024-04-24at12.48.43PM%20(1).webp",
      "https://blinkbuy.s3.amazonaws.com/WhatsAppImage2024-04-24at12.48.42PM.webp",
    ],
    tags: [
      "act-men-so24",
      "All-MenCat23",
      "AllCoordPDP",
      "Co-ord",
      "discount",
      "good",
      "Jog.cordfeb23",
      "M.cord",
      "m.elevated_coords",
      "m.mono",
      "male",
      "Men",
      "Menmccord",
      "Mennewcoll771",
      "Mens Coord set",
      "Mono-coords",
      "MSS-Feb24",
      "NBB25NBB5",
      "NOCoord",
      "ret",
      "Size-L",
      "Size-M",
      "Size-S",
      "Size-XL",
      "Size-XXL",
      "Size-XXXL",
    ],
    sizes: ["S", "M", "L", "XL", "XXL"],
  },
  {
    title: "Oversized Cooper Utility Co-Ord",
    discountedPrice: 1599,
    price: 2999,
    reviewsAverage: null,
    reviewsCount: null,
    colors: ["Olive Green"],
    images: [
      "https://blinkbuy.s3.amazonaws.com/WhatsAppImage2024-04-24at3.59.09PM_a084995a-759d-4b22-a6a1-53a80a09e9f1.webp",
      "https://blinkbuy.s3.amazonaws.com/WhatsAppImage2024-04-24at2.59.05PM_0c757c63-da19-4497-928f-a4dd107b8ad4.webp",
      "https://blinkbuy.s3.amazonaws.com/WhatsAppImage2024-04-24at2.33.30PM.webp",
      "https://blinkbuy.s3.amazonaws.com/WhatsAppImage2024-04-24at2.53.58PM_fa4f5439-8320-4f54-bb7c-ffc640bec4c1.webp",
      "https://blinkbuy.s3.amazonaws.com/WhatsAppImage2024-04-24at2.33.30PM_1.webp",
      "https://blinkbuy.s3.amazonaws.com/7_636d7f82-48ce-4a49-8267-cfb6cae005c2.webp",
    ],
    tags: [
      "act-men-so24",
      "All-MenCat23",
      "AllCoordPDP",
      "Co-ord",
      "discount",
      "good",
      "Jog.cordfeb23",
      "M.cord",
      "m.elevated_coords",
      "m.mono",
      "male",
      "Men",
      "Menmccord",
      "Mennewcoll771",
      "Mens Coord set",
      "Mono-coords",
      "MSS-Feb24",
      "NBB25NBB5",
      "NOCoord",
      "oversized",
      "ret",
      "Size-L",
      "Size-M",
      "Size-S",
      "Size-XL",
      "Size-XXL",
      "Size-XXXL",
    ],
    sizes: ["S", "M", "L", "XL", "XXL"],
  },
  {
    title: "Roger Men's Co-Ord Sets",
    discountedPrice: 1599,
    price: 2999,
    reviewsAverage: null,
    reviewsCount: null,
    colors: ["Navy"],
    images: [
      "https://blinkbuy.s3.amazonaws.com/IA00729509-M-1-092421-IS2-1-4M_625x_c62f9d8e-b68d-4629-88ca-f1b0a202502c.webp",
      "https://blinkbuy.s3.amazonaws.com/Roger-1.webp",
      "https://blinkbuy.s3.amazonaws.com/Roger-1.webp",
      "https://blinkbuy.s3.amazonaws.com/Roger-1.webp",
      "https://blinkbuy.s3.amazonaws.com/rogernavy-4.webp",
    ],
    tags: [
      "31-80Men",
      "act-men-so24",
      "All-MenCat23",
      "AllCoordPDP",
      "Best_Seller_NB",
      "Co-ord",
      "discount",
      "good",
      "Jog.Cord23",
      "M.cord",
      "male",
      "MCORDPUR77199",
      "Men",
      "mennoberodrop4",
      "Mens Coord set",
      "MSS-Feb24",
      "NBB25NBB5",
      "NOCoord",
      "ret",
      "Size-L",
      "Size-M",
      "Size-S",
      "Size-XL",
      "Size-XXL",
      "Size-XXXL",
      "SochMencat",
      "Socioh-MenCat",
      "SociohJogCord",
      "SummerCordMen",
      "testinv",
      "topM.cordBot",
    ],
    sizes: ["S", "M", "L", "XL", "XXL"],
  },
  {
    title: "Hwak Men's Co-Ord Sets",
    discountedPrice: 1599,
    price: 3199,
    reviewsAverage: null,
    reviewsCount: null,
    colors: ["Maroon"],
    images: [
      "https://blinkbuy.s3.amazonaws.com/4_0a0a6d1a-5b78-4f02-b0bc-a22196344f21.webp",
      "https://blinkbuy.s3.amazonaws.com/2_7e2f9e6a-04a1-4c89-bfd7-f5906ee52db5.webp",
      "https://blinkbuy.s3.amazonaws.com/5_dee6cb9e-c26b-441d-a369-82f5abfa9e38.webp",
      "https://blinkbuy.s3.amazonaws.com/1_3a7164f3-5dde-4202-928c-e5adffddd7aa.webp",
      "https://blinkbuy.s3.amazonaws.com/3_bceb7d0b-4930-4457-87e7-ba7a1ea9e7c1.webp",
      "https://blinkbuy.s3.amazonaws.com/WhatsAppImage2024-04-06at2.09.47PM.webp",
      "https://blinkbuy.s3.amazonaws.com/16377337168d9e8562d28796b7fc4c80b0378dafea_1_8512163e-6460-4ac7-8cbe-7ac75efce174.webp",
    ],
    tags: [
      "act-men-so24",
      "All-MenCat23",
      "AllCoordPDP",
      "Co-ord",
      "discount",
      "good",
      "M.cord",
      "male",
      "MCORDPUR77199",
      "Men",
      "mennoberodrop4",
      "Mens Coord set",
      "MSS-Feb24",
      "NBB25NBB5",
      "ret",
      "Size-L",
      "Size-M",
      "Size-S",
      "Size-XL",
      "Size-XXL",
      "Size-XXXL",
      "SochMencat",
      "SummerCordMen",
      "SummerCordMens",
      "testinv",
    ],
    sizes: ["S", "M", "L", "XL", "XXL"],
  },
  {
    title: "Fabien Men's Co-Ords",
    discountedPrice: 1999,
    price: 3999,
    reviewsAverage: null,
    reviewsCount: null,
    colors: null,
    images: [
      "https://blinkbuy.s3.amazonaws.com/07-0802.jpg",
      "https://blinkbuy.s3.amazonaws.com/1_7_13754903-b2d7-407c-b739-716f6ff31164.webp",
      "https://blinkbuy.s3.amazonaws.com/07-0032.webp",
      "https://blinkbuy.s3.amazonaws.com/2_6_ebeff0f6-cfa9-47bd-af25-bfc9d4e004ac.webp",
      "https://blinkbuy.s3.amazonaws.com/07-0029.webp",
      "https://blinkbuy.s3.amazonaws.com/3_4.webp",
    ],
    tags: [
      "act-men-so24",
      "Airportcoords",
      "AllCoordPDP",
      "Clearance-Men-Jan23",
      "Co-ord",
      "discount",
      "good",
      "hoodiedropsale",
      "M.cord",
      "male",
      "MAutumn",
      "MCORDPUR77199",
      "Men",
      "Mens Coord set",
      "MensButton",
      "MSS-Feb24",
      "NBB25NBB5",
      "NOCoord",
      "ret",
      "Size-L",
      "Size-M",
      "Size-S",
      "Size-XL",
      "Size-XXL",
      "Size-XXXL",
      "SochMencat",
      "Socioh-MenCat",
      "SociohJogCord",
      "testinv",
      "topM.cordBot",
    ],
    sizes: ["S", "XXL"],
  },
  {
    title: "Oversized Cooper Utility Co-Ord",
    discountedPrice: 1599,
    price: 2999,
    reviewsAverage: null,
    reviewsCount: null,
    colors: ["Powder Blue"],
    images: [
      "https://blinkbuy.s3.amazonaws.com/6_d5a62ffd-51dd-4109-8c14-39954328a9bb.webp",
      "https://blinkbuy.s3.amazonaws.com/5_79f8caf6-8702-498d-a890-7c8714fb4c4d.webp",
      "https://blinkbuy.s3.amazonaws.com/9_a0b08bfa-f409-43f8-b0d3-d9b8d9dd0b79.webp",
      "https://blinkbuy.s3.amazonaws.com/2_bd8a7f57-0386-4ea2-8b57-bf2fc5b4809a.webp",
      "https://blinkbuy.s3.amazonaws.com/EBM-91_bcc617a2-1a2d-459f-8b0c-2c59756bb3d0.webp",
    ],
    tags: [
      "act-men-so24",
      "All-MenCat23",
      "AllCoordPDP",
      "Co-ord",
      "discount",
      "good",
      "Jog.cordfeb23",
      "M.cord",
      "m.elevated_coords",
      "m.mono",
      "male",
      "Men",
      "Menmccord",
      "Mennewcoll771",
      "Mens Coord set",
      "Mono-coords",
      "MSS-Feb24",
      "NBB25NBB5",
      "NOCoord",
      "oversized",
      "ret",
      "Size-L",
      "Size-M",
      "Size-S",
      "Size-XL",
      "Size-XXL",
      "Size-XXXL",
    ],
    sizes: ["S", "M", "L", "XL", "XXL"],
  },
];

export const oversized_tshirts = [
  {
    title: "Oversized T-Shirt",
    discountedPrice: 599,
    price: 999,
    reviewsAverage: 4.4,
    reviewsCount: 342,
    colors: ["Black"],
    images: [
      "https://blinkbuy.s3.amazonaws.com/PowderBlue_946fe8da-0ea9-4bd9-9c66-68bb80828cb2.webp",
      "https://blinkbuy.s3.amazonaws.com/White_0126fd43-6c05-438b-a939-b8039c9f44a2.webp",
      "https://blinkbuy.s3.amazonaws.com/AloeGreenjpg_9d7c7c33-14db-4bb2-8890-7afae8b69883.webp",
      "https://blinkbuy.s3.amazonaws.com/GreyMelanage_2ef2652d-9400-41ea-85d2-d9f5003f8848.webp",
      "https://blinkbuy.s3.amazonaws.com/Black.webp",
    ],
    tags: [
      "1P2@999",
      "act-men-so24",
      "All-MenCat23",
      "app_size_chart",
      "B2G1allmen",
      "Best_Seller_NB",
      "good",
      "M.realxedfit2",
      "m.relaxedfit",
      "M.relaxedfit2",
      "m.relaxedfit3",
      "M.Relaxedplain",
      "M.Relaxedprint",
      "Men relaxed fit tshirt",
      "mw.relaxedfit",
      "NBB25NBB5",
      "OT@699",
      "P2Tee@999",
      "PDPtextOT",
      "ret",
      "Size-L",
      "Size-M",
      "Size-S",
      "Size-XL",
      "Size-XXL",
      "Size-XXXL",
      "TrendyMensMM",
      "w.relaxedfit",
      "w.relaxedfit2",
    ],
    sizes: ["S", "M", "L", "XL", "XXL"],
  },
  {
    title: "Authentic Oversized T-Shirt",
    discountedPrice: 599,
    price: 999,
    reviewsAverage: 4.5,
    reviewsCount: 69,
    colors: ["Wine Red", "Red"],
    images: [
      "https://blinkbuy.s3.amazonaws.com/be-fearless_ef99cfc5-19c9-4bcb-a461-050d4886a3b7.webp",
      "https://blinkbuy.s3.amazonaws.com/be-fearless_d86f9165-ff7a-4258-b4c5-3456a7c67149_4_1.webp",
    ],

    tags: [
      "act-men-so24",
      "app_size_chart",
      "good",
      "M.realxedfit2",
      "m.relaxedfit",
      "M.relaxedfit2",
      "m.relaxedfit3",
      "Men relaxed fit tshirt",
      "mw.relaxedfit",
      "NBB25NBB5",
      "OT@699",
      "P2Tee@999",
      "PDPtextOT",
      "ret",
      "Size-L",
      "Size-M",
      "Size-S",
      "Size-XL",
      "Size-XXL",
      "Size-XXXL",
    ],
    sizes: ["S", "M", "L", "XL", "XXL"],
  },

  {
    title: "Grow Oversized T-Shirt",
    discountedPrice: 599,
    price: 999,
    reviewsAverage: 4.5,
    reviewsCount: 43,
    colors: ["Avocado"],
    images: [
      "https://blinkbuy.s3.amazonaws.com/71_be3a4eae-250b-4126-9eaa-66fd7f8048d2.webp",
      "https://blinkbuy.s3.amazonaws.com/grow_2e0d3024-3e8b-4765-8c99-073599f7ed0a.webp",
      "https://blinkbuy.s3.amazonaws.com/WhatsAppImage2024-01-04at1.55.37PM_1.webp",
    ],
    tags: [
      "1P2@999",
      "act-men-so24",
      "app_size_chart",
      "B2G1allmenDraft",
      "good",
      "M.realxedfit2",
      "m.relaxedfit",
      "M.Relaxedfit2",
      "m.relaxedfit3",
      "Men relaxed fit tshirt",
      "mw.relaxedfit",
      "NBB25NBB5",
      "OT@699",
      "P2Tee@999",
      "PDPtextOT",
      "RelaxedPrint",
      "ret",
      "Size-L",
      "Size-M",
      "Size-S",
      "Size-XL",
      "Size-XXL",
      "Size-XXXL",
    ],
    sizes: ["S", "M", "L", "XL", "XXL"],
  },
  {
    title: "Ikigai Oversized T-Shirt",
    discountedPrice: 599,
    price: 999,
    reviewsAverage: null,
    reviewsCount: null,
    colors: ["Cannoli", "White"],
    images: [
      "https://blinkbuy.s3.amazonaws.com/ikagi.webp",
      "https://blinkbuy.s3.amazonaws.com/WhatsAppImage2024-02-24at12.28.37PM_8.webp",
      "https://blinkbuy.s3.amazonaws.com/ikagi_7a5a47f5-be95-4139-a8c8-a1aca31ac1f1.webp",
      "https://blinkbuy.s3.amazonaws.com/31.webp",
    ],
    tags: [
      "1P2@999",
      "act-men-so24",
      "app_size_chart",
      "B2G1allmenDraft",
      "good",
      "M.realxedfit2",
      "m.relaxedfit",
      "M.relaxedfit2",
      "m.relaxedfit3",
      "Men relaxed fit tshirt",
      "mw.relaxedfit",
      "NBB25NBB5",
      "OT@699",
      "P2Tee@999",
      "PDPtextOT",
      "RelaxedPrint",
      "ret",
      "Size-L",
      "Size-M",
      "Size-S",
      "Size-XL",
      "Size-XXL",
      "Size-XXXL",
    ],
    sizes: ["S", "M", "L", "XL", "XXL"],
  },
  {
    title: "Wandersoul Oversized T-Shirt",
    discountedPrice: 599,
    price: 999,
    reviewsAverage: null,
    reviewsCount: null,
    colors: ["Marine"],
    images: [
      "https://blinkbuy.s3.amazonaws.com/wandersoul_c2404de7-6a28-4c84-9359-6c984c8f07d7.webp",
      "https://blinkbuy.s3.amazonaws.com/20%20(1).webp",
      "https://blinkbuy.s3.amazonaws.com/20.webp",
      "https://blinkbuy.s3.amazonaws.com/wandersoul_c2404de7-6a28-4c84-9359-6c984c8f07d7%20(1).webp",
    ],
    tags: [
      "act-men-so24",
      "app_size_chart",
      "B2G1allmenDraft",
      "good",
      "m.relaxedfit",
      "M.relaxedfit2",
      "m.relaxedfit3",
      "Men relaxed fit tshirt",
      "mw.relaxedfit",
      "NBB25NBB5",
      "OT@699",
      "P2Tee@999",
      "PDPtextOT",
      "ret",
      "Size-L",
      "Size-M",
      "Size-S",
      "Size-XL",
      "Size-XXL",
      "Size-XXXL",
    ],
    sizes: ["S", "M", "L", "XL", "XXL"],
  },
  {
    title: "RIse Oversized T-Shirt",
    discountedPrice: 599,
    price: 999,
    reviewsAverage: null,
    reviewsCount: null,
    colors: ["Blush"],
    images: [
      "https://blinkbuy.s3.amazonaws.com/WhatsAppImage2024-02-01at5.48.12PM_1_1%20(1).webp",
      "https://blinkbuy.s3.amazonaws.com/WhatsAppImage2024-03-30at1.17.39PM.webp",
      "https://blinkbuy.s3.amazonaws.com/WhatsAppImage2024-02-01at5.48.12PM_1_1.webp",
      "https://blinkbuy.s3.amazonaws.com/WhatsAppImage2024-03-30at1.17.39PM%20(1).webp",
    ],
    tags: [
      "act-men-so24",
      "app_size_chart",
      "B2G1allmenDraft",
      "good",
      "M.realxedfit2",
      "m.relaxedfit",
      "M.relaxedfit2",
      "m.relaxedfit3",
      "Men relaxed fit tshirt",
      "mw.relaxedfit",
      "NBB25NBB5",
      "OT@699",
      "P2Tee@999",
      "PDPtextOT",
      "ret",
      "Size-L",
      "Size-M",
      "Size-S",
      "Size-XL",
      "Size-XXL",
      "Size-XXXL",
      "w.relaxedfit2",
    ],
    sizes: ["M", "L", "XL", "XXL"],
  },
  {
    title: "Upward & Forward Oversized T-Shirt",
    discountedPrice: 599,
    price: 999,
    reviewsAverage: 4.4,
    reviewsCount: 342,
    colors: ["Marine"],
    images: [
      "https://blinkbuy.s3.amazonaws.com/53_29d3294e-7fed-437f-b207-f164a0c7ccc8.webp",
      "https://blinkbuy.s3.amazonaws.com/upward-forward_c9696a16-f36e-48b7-9ba1-791092f23dfa.webp",
    ],
    tags: [
      "1P2@999",
      "act-men-so24",
      "app_size_chart",
      "B2G1allmenDraft",
      "good",
      "M.realxedfit2",
      "m.relaxedfit",
      "M.relaxedfit2",
      "m.relaxedfit3",
      "Men relaxed fit tshirt",
      "mw.relaxedfit",
      "NBB25NBB5",
      "OT@699",
      "P2Tee@999",
      "PDPtextOT",
      "RelaxedPrint",
      "ret",
      "Size-L",
      "Size-M",
      "Size-S",
      "Size-XL",
      "Size-XXL",
      "Size-XXXL",
      "w.relaxedfit",
      "w.relaxedfit2",
    ],
    sizes: ["S", "M", "L", "XL", "XXL"],
  },
  {
    title: "Forever Chasing Sunset Oversized T-Shirt",
    discountedPrice: 599,
    price: 999,
    reviewsAverage: null,
    reviewsCount: null,
    colors: ["Honeycomb"],
    images: [
      "https://blinkbuy.s3.amazonaws.com/WhatsAppImage2024-03-30at12.17.29PM_1%20(1).webp",
      "https://blinkbuy.s3.amazonaws.com/WhatsAppImage2024-03-30at12.12.06PM_1.webp",
      "https://blinkbuy.s3.amazonaws.com/WhatsAppImage2024-03-30at12.17.29PM_1.webp",
      "https://blinkbuy.s3.amazonaws.com/WhatsAppImage2024-03-30at12.12.06PM_1%20(1).webp",
    ],
    tags: [
      "act-men-so24",
      "app_size_chart",
      "B2G1allmenDraft",
      "good",
      "M.realxedfit2",
      "m.relaxedfit",
      "M.relaxedfit2",
      "m.relaxedfit3",
      "Men relaxed fit tshirt",
      "mw.relaxedfit",
      "NBB25NBB5",
      "OT@699",
      "P2Tee@999",
      "PDPtextOT",
      "ret",
      "Size-L",
      "Size-M",
      "Size-S",
      "Size-XL",
      "Size-XXL",
      "Size-XXXL",
      "w.relaxedfit2",
    ],
    sizes: ["S", "M", "L", "XL", "XXL"],
  },
  {
    title: "Mirage Oversized T-Shirt",
    discountedPrice: 599,
    price: 999,
    reviewsAverage: null,
    reviewsCount: null,
    colors: ["White"],
    images: [
      "https://blinkbuy.s3.amazonaws.com/mirage_59e0eaee-2d4a-4032-a460-e35086256869.webp",
      "https://blinkbuy.s3.amazonaws.com/mirage2.webp",
      "https://blinkbuy.s3.amazonaws.com/34.webp",
      "https://blinkbuy.s3.amazonaws.com/34.webp",
    ],
    tags: [
      "act-men-so24",
      "app_size_chart",
      "B2G1allmenDraft",
      "good",
      "M.realxedfit2",
      "m.relaxedfit",
      "M.relaxedfit2",
      "m.relaxedfit3",
      "Men relaxed fit tshirt",
      "mw.relaxedfit",
      "NBB25NBB5",
      "OT@699",
      "P2Tee@999",
      "PDPtextOT",
      "ret",
      "Size-L",
      "Size-M",
      "Size-S",
      "Size-XL",
      "Size-XXL",
      "Size-XXXL",
    ],
    sizes: ["S", "M", "L", "XL", "XXL"],
  },
  {
    title: "Discover Oversized T-Shirt",
    discountedPrice: 599,
    price: 999,
    reviewsAverage: 4.5,
    reviewsCount: 44,
    colors: ["Aloe Green"],
    images: [
      "https://blinkbuy.s3.amazonaws.com/discover_728a50ff-02f8-4950-9a10-fabbe22fa466.webp",
      "https://blinkbuy.s3.amazonaws.com/WhatsAppImage2023-12-06at11.36.31AM_2_1.webp",
    ],
    tags: [
      "1P2@999",
      "act-men-so24",
      "app_size_chart",
      "B2G1allmenDraft",
      "good",
      "M.realxedfit2",
      "m.relaxedfit",
      "M.Relaxedfit2",
      "m.relaxedfit3",
      "Men relaxed fit tshirt",
      "mw.relaxedfit",
      "NBB25NBB5",
      "OT@699",
      "P2Tee@999",
      "PDPtextOT",
      "RelaxedPrint",
      "ret",
      "Size-L",
      "Size-M",
      "Size-S",
      "Size-XL",
      "Size-XXL",
      "Size-XXXL",
    ],
    sizes: ["M", "L", "XL", "XXL"],
  },
];
